site_name: "X1/9e - Technische Dokumentation"
site_description: "Dokumentation für den Elektro-Umbau des Fiat Bertone X1/9 nach TÜV-Vorgaben"
site_author: "Frank Hielscher"

theme:
  name: material
  custom_dir: theme
  language: de
  font:
    text: Montserrat
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: amber
      toggle:
        icon: material/weather-night
        name: In den dunklen Modus wechseln
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: In den hellen Modus wechseln
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - content.code.copy

extra_css:
  - stylesheets/custom.css
  - https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/contrib/auto-render.min.js

markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - def_list

nav:
  - Home: index.md
  - Inhalt:
    - 1 Technische Kurzbeschreibung: kurzbeschreibung.md
    - 2 Funktionssicherheit: funktionssicherheit.md
    - 3 Elektrische Sicherheit: elektrische_sicherheit.md
    - 4 Sicherheit des Energiespeichers: sicherheit_des_energiespeichers.md
    - 5 Umweltschutz und Umweltverträglichkeit: umweltschutz_und_vertraeglichkeit.md
    - 6 Umfassender Personenschutz - Schutz für Dritte: umfassender_personenschutz.md
  - Anhang:
    - Anhang: anhang.md

plugins:
  - search