site_name: "X1/9e - Technische Dokumentation"
site_author: "Frank Hielscher"

theme:
  name: material
  language: de
  font:
    text: Montserrat
    code: Roboto Mono
  palette:
    - scheme: slate
      primary: black
      accent: amber

extra_css:
  - stylesheets/custom.css

markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - admonition
  - def_list
  - toc:                    # wichtig für gutes TOC
      permalink: true
  - pymdownx.arithmatex:     # ← wichtig für Formeln
      generic: true

nav:
  - Home: index.md
  - Technische Kurzbeschreibung: kurzbeschreibung.md
  - Funktionssicherheit: funktionssicherheit.md
  - Elektrische Sicherheit: elektrische_sicherheit.md
  - Sicherheit des Energiespeichers: sicherheit_des_energiespeichers.md
  - Umweltschutz und Umweltverträglichkeit: umweltschutz_und_vertraeglichkeit.md
  - Umfassender Personenschutz - Schutz für Dritte: umfassender_personenschutz.md

plugins:
  - search
  - print-site:                  # ← als letztes Plugin!
      enumerate_headings: true
      enumerate_headings_depth: 4
      enumerate_figures: true
      add_cover_page: true       # nutzt index.md als Deckblatt
      include_css: true 
      # toc_title: "Inhaltsverzeichnis"
      # add_full_urls: false

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js